server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh  # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**  # 断言，路径相匹配进行路由
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/create/**
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver
#            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
#            - Cookie=chocolate, ch.p
#            - Header=X-Request-Id, \d+
#            - Host=**.somehost.org,**.anotherhost.org
#            - Method=GET,POST
#            - Query=red, gree.
#            - RemoteAddr=192.168.1.1/24
#            - Weight=group1, 2


eureka:
  instance:
    hostname: cloue-gateway-service     # eureka服务端的实力名称
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
#      defaultZone: http://eureka7001.com:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
